# Generated by Django 4.0.2 on 2022-06-24 13:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_action_alter_course_description_alter_rating_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 24, 13, 52, 48, 264083, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 24, 13, 53, 12, 557058, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
